### ISSUE TITLE
Can't reuse domain name in dns example for new service

### ISSUE THREAD

**Issue by benjaminbollen** [maidsafe/safe_dns#33]
This is probably correct behaviour, but gives a weird user experience: i first create a www.ben and later a blog.ben, then I get an error that the domain and service are already registered.  I assume that this is because I am using a new client with "start over" and access to the domain name "ben" is denied?

**Comment by ustulation** [comment]
Do you restart the example ? Because as long as you are running the same example (without quitting) you should be able to add new services and delete previously added ones. Ofcourse once you quit the example and start again, you are prompted to create a new account. This is created with all the new maid keys etc so there is no way you can update anything that the previous client had put, which is correct.
On the other hand, if the new client selects option to only simulate the parsing of url by the browser (Option <7> as when this was written) then the client can retrieve the home-page file for the requested service from the requested Dns, which is correct again.

So i don't understand where is the bug in this - this is all the example wants to demonstrate. If you wanted a choice to re-login to the previously created account, that is shown in the `safe_client`'s `self_authentication` example, as it is out of scope and unnecessary here.

**Comment by benjaminbollen** [comment]
I don't close the example.  I will retest later, but I was not able to do www.ben and then restart and do blog.ben for example
